version: '3'
services:
  otterwiki:
    image: redimp/otterwiki:2
    build: ../../..
    restart: unless-stopped
    ports:
      # forward the http port to 8080
      - "8080:80"
    environment:
      - SITE_NAME=Otter Header Auth
      - AUTH_METHOD=PROXY_HEADER
      - AUTH_HEADERS_USERNAME=x-otterwiki-name # Optional: change the headers' names
      - READ_ACCESS=APPROVED
      - WRITE_ACCESS=APPROVED
      - ATTACHMENT_ACCESS=APPROVED
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
